import React, { useCallback, useEffect, useState } from 'react';
import { getAuthHeaders } from '../utils/scoreboardApi';

const input = { padding: '7px 9px', border: '1px solid #d1d5db', borderRadius: 7, color: '#111827', width: '100%', boxSizing: 'border-box' };
const card = { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 16, marginBottom: 14 };
const orderStates = ['nuevo', 'confirmado', 'preparando', 'listo_retiro', 'enviado', 'entregado', 'cancelado'];

export default function AdminSedeShopSection({ apiBaseUrl, sedeId, monedaSede = 'ARS' }) {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setError(''); const res = await fetch(`${apiBaseUrl}/api/sedes/${sedeId}/shop/admin`, { headers: await getAuthHeaders() }); const json = await res.json(); if (!res.ok) throw new Error(json.error); setData(json); } catch (e) { setError(e.message || 'No se pudo cargar la tienda'); } }, [apiBaseUrl, sedeId]);
  useEffect(() => { void load(); }, [load]);
  const saveConfig = async () => { setSaving(true); try { const res = await fetch(`${apiBaseUrl}/api/sedes/${sedeId}/tienda-config`, { method: 'PUT', headers: { ...(await getAuthHeaders()), 'Content-Type': 'application/json' }, body: JSON.stringify(data.config) }); if (!res.ok) throw new Error('No se pudo guardar'); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const saveOffer = async (offer) => { setSaving(true); try { const res = await fetch(`${apiBaseUrl}/api/sedes/${sedeId}/shop/offers/${offer.id}`, { method: 'PATCH', headers: { ...(await getAuthHeaders()), 'Content-Type': 'application/json' }, body: JSON.stringify({ activo: offer.activo, stock: offer.stock, precio: offer.precio, moneda: offer.moneda }) }); if (!res.ok) throw new Error('No se pudo guardar producto'); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const updateOrder = async (id, estado) => { setSaving(true); try { const res = await fetch(`${apiBaseUrl}/api/sedes/${sedeId}/shop/orders/${id}`, { method: 'PATCH', headers: { ...(await getAuthHeaders()), 'Content-Type': 'application/json' }, body: JSON.stringify({ estado }) }); if (!res.ok) throw new Error('No se pudo actualizar pedido'); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  if (!data) return <div style={card}>{error || 'Cargando Mi Padbol Match Shop…'}</div>;
  const c = data.config;
  return <div>
    {error ? <p style={{ color: '#b91c1c' }}>{error}</p> : null}
    <div style={card}><h3 style={{ marginTop: 0 }}>Mi Padbol Match Shop</h3><p style={{ color: '#64748b' }}>Configuración exclusiva de esta sede. No modifica el catálogo maestro.</p><label>Estado <select value={c.estado} onChange={e => setData(d => ({ ...d, config: { ...d.config, estado: e.target.value } }))} style={input}><option value="active">Activa</option><option value="opening_soon">Próximamente</option><option value="paused">Pausada</option></select></label><div style={{ display: 'flex', gap: 16, marginTop: 12 }}><label><input type="checkbox" checked={!!c.retiro_en_sede} onChange={e => setData(d => ({ ...d, config: { ...d.config, retiro_en_sede: e.target.checked } }))} /> Retiro en sede</label><label><input type="checkbox" checked={!!c.entrega_local} onChange={e => setData(d => ({ ...d, config: { ...d.config, entrega_local: e.target.checked } }))} /> Entrega local</label></div>{c.entrega_local ? <label style={{ display: 'block', marginTop: 12 }}>Radio de entrega (km)<input type="number" value={c.radio_entrega_km || ''} onChange={e => setData(d => ({ ...d, config: { ...d.config, radio_entrega_km: e.target.value } }))} style={input} /></label> : null}<button disabled={saving} onClick={saveConfig} style={{ marginTop: 14 }}>Guardar entrega</button></div>
    <div style={card}><h3 style={{ marginTop: 0 }}>Productos autorizados</h3>{data.offers.length ? data.offers.map((o, i) => <div key={o.id} style={{ borderTop: i ? '1px solid #eee' : 0, paddingTop: i ? 12 : 0, marginTop: i ? 12 : 0 }}><strong>{o.product?.nombre}</strong><div style={{ display: 'flex', gap: 8, marginTop: 8 }}><input type="number" value={o.precio ?? ''} onChange={e => setData(d => ({ ...d, offers: d.offers.map(x => x.id === o.id ? { ...x, precio: e.target.value } : x) }))} style={input} placeholder="Precio"/><input type="number" value={o.stock ?? 0} onChange={e => setData(d => ({ ...d, offers: d.offers.map(x => x.id === o.id ? { ...x, stock: e.target.value } : x) }))} style={input} placeholder="Stock"/><input value={o.moneda || monedaSede} onChange={e => setData(d => ({ ...d, offers: d.offers.map(x => x.id === o.id ? { ...x, moneda: e.target.value } : x) }))} style={input}/></div><label><input type="checkbox" checked={!!o.activo} onChange={e => setData(d => ({ ...d, offers: d.offers.map(x => x.id === o.id ? { ...x, activo: e.target.checked } : x) }))} /> Visible para venta</label><button disabled={saving} onClick={() => saveOffer(o)}>Guardar</button></div>) : <p>No hay productos autorizados todavía.</p>}</div>
    <div style={card}><h3 style={{ marginTop: 0 }}>Pedidos</h3><p><b>{data.metrics.pendientes}</b> pendientes · <b>{data.metrics.entregados}</b> entregados · Total informativo: {data.metrics.total_informativo} {monedaSede}</p>{data.orders.map(o => <div key={o.id} style={{ borderTop: '1px solid #eee', padding: '10px 0' }}><b>{o.codigo}</b> · {o.fulfillment_type === 'pickup' ? 'Retiro' : 'Entrega'} · {o.total} {o.moneda}<br/><select value={o.estado} onChange={e => updateOrder(o.id, e.target.value)}>{orderStates.map(s => <option key={s} value={s}>{s}</option>)}</select> <button onClick={() => window.print()}>Imprimir etiqueta</button></div>)}</div>
  </div>;
}
